In [150]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [151]:
from urllib.request import urlopen
from bs4 import BeautifulSoup

In [152]:
url = "https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data#covid19-container"
html=urlopen(url)

In [153]:
html

In [154]:
soup = BeautifulSoup(html, 'lxml')
type(soup)

bs4.BeautifulSoup

In [155]:
a=soup.find_all('a')

In [156]:
tab=soup.find_all('th')

In [157]:
import re
lst=[]
table = soup.find('tbody') 
for i in table.stripped_strings:
    text=repr(i)
    if re.search("[[\S]]",text):
        continue
    
    lst.append(text)

In [158]:
for i in lst:
    if i=="'Ref.'":
        lst.remove(i)

In [159]:
lst

["'Locations'",
 "'Cases'",
 "'Deaths'",
 "'Recov.'",
 "'229'",
 "'4,563,458'",
 "'308,165'",
 "'1,649,275'",
 "'United States'",
 "'1,473,415'",
 "'88,237'",
 "'260,146'",
 "'Russia'",
 "'272,043'",
 "'2,537'",
 "'63,166'",
 "'United Kingdom'",
 "'236,711'",
 "'33,998'",
 "'No data'",
 "'Spain'",
 "'230,183'",
 "'27,459'",
 "'144,783'",
 "'Italy'",
 "'223,885'",
 "'31,610'",
 "'120,205'",
 "'Brazil'",
 "'220,291'",
 "'14,962'",
 "'84,970'",
 "'Germany'",
 "'175,699'",
 "'8,001'",
 "'151,700'",
 "'Turkey'",
 "'146,457'",
 "'4,055'",
 "'106,133'",
 "'France'",
 "'141,919'",
 "'27,529'",
 "'60,448'",
 "'Iran'",
 "'116,635'",
 "'6,902'",
 "'91,836'",
 "'India'",
 "'85,940'",
 "'2,752'",
 "'30,153'",
 "'Peru'",
 "'84,495'",
 "'2,392'",
 "'27,147'",
 "'China'",
 "'82,941'",
 "'4,633'",
 "'78,219'",
 "'Canada'",
 "'74,613'",
 "'5,562'",
 "'36,895'",
 "'Belgium'",
 "'54,644'",
 "'8,959'",
 "'14,301'",
 "'Saudi Arabia'",
 "'49,176'",
 "'292'",
 "'21,869'",
 "'Mexico'",
 "'45,032'",
 "'4,767'",
 "'30,451'",
 "'Netherlands'",
 "'43,681'",
 "'5,643'",
 "'No data'",
 "'Chile'",
 "'39,542'",
 "'394'",
 "'16,614'",
 "'Pakistan'",
 "'38,799'",
 "'834'",
 "'10,880'",
 "'Ecuador'",
 "'31,467'",
 "'3,594'",
 "'3,433'",
 "'Switzerland'",
 "'30,514'",
 "'1,595'",
 "'27,200'",
 "'Qatar'",
 "'29,425'",
 "'14'",
 "'3,546'",
 "'Sweden'",
 "'29,207'",
 "'3,646'",
 "'4,971'",
 "'Belarus'",
 "'28,681'",
 "'160'",
 "'9,498'",
 "'Portugal'",
 "'28,583'",
 "'1,190'",
 "'3,328'",
 "'Singapore'",
 "'27,356'",
 "'21'",
 "'7,248'",
 "'Ireland'",
 "'23,956'",
 "'1,518'",
 "'19,470'",
 "'United Arab Emirates'",
 "'21,831'",
 "'210'",
 "'7,328'",
 "'Bangladesh'",
 "'20,065'",
 "'298'",
 "'3,882'",
 "'Poland'",
 "'18,016'",
 "'907'",
 "'6,918'",
 "'Ukraine'",
 "'17,858'",
 "'497'",
 "'4,906'",
 "'Romania'",
 "'16,704'",
 "'1,081'",
 "'9,574'",
 "'Israel'",
 "'16,589'",
 "'266'",
 "'12,587'",
 "'Indonesia'",
 "'16,496'",
 "'1,076'",
 "'3,803'",
 "'Japan'",
 "'16,253'",
 "'729'",
 "'10,809'",
 "'Austria'",
 "'16,135'",
 "'628'",
 "'14,471'",
 "'Colombia'",
 "'14,216'",
 "'546'",
 "'3,460'",
 "'South Africa'",
 "'13,524'",
 "'247'",
 "'6,083'",
 "'Kuwait'",
 "'12,860'",
 "'96'",
 "'3,640'",
 "'Philippines'",
 "'12,305'",
 "'817'",
 "'2,561'",
 "'Dominican Republic'",
 "'11,739'",
 "'424'",
 "'3,3557'",
 "'Egypt'",
 "'11,228'",
 "'592'",
 "'3,363'",
 "'South Korea'",
 "'11,037'",
 "'262'",
 "'9,851'",
 "'Denmark'",
 "'10,791'",
 "'537'",
 "'8,959'",
 "'Serbia'",
 "'10,438'",
 "'225'",
 "'4,301'",
 "'Panama'",
 "'9,268'",
 "'266'",
 "'6,080'",
 "'Czech Republic'",
 "'8,406'",
 "'295'",
 "'5,381'",
 "'Norway'",
 "'8,219'",
 "'232'",
 "'7,114'",
 "'Argentina'",
 "'7,121'",
 "'353'",
 "'2,372'",
 "'Australia'",
 "'7,038'",
 "'98'",
 "'6,362'",
 "'Malaysia'",
 "'6,872'",
 "'113'",
 "'5,512'",
 "'Morocco'",
 "'6,652'",
 "'190'",
 "'3,400'",
 "'Algeria'",
 "'6,629'",
 "'536'",
 "'3,271'",
 "'Bahrain'",
 "'6,583'",
 "'12'",
 "'2,640'",
 "'Afghanistan'",
 "'6,402'",
 "'168'",
 "'778'",
 "'Finland'",
 "'6,228'",
 "'287'",
 "'4,300'",
 "'Kazakhstan'",
 "'5,850'",
 "'34'",
 "'2,707'",
 "'Moldova'",
 "'5,745'",
 "'202'",
 "'2,280'",
 "'Ghana'",
 "'5,638'",
 "'28'",
 "'1,460'",
 "'Nigeria'",
 "'5,450'",
 "'171'",
 "'1,320'",
 "'Oman'",
 "'4,625'",
 "'19'",
 "'1,350'",
 "'Armenia'",
 "'4,283'",
 "'55'",
 "'1,791'",
 "'Luxembourg'",
 "'3,923'",
 "'104'",
 "'3,682'",
 "'Bolivia'",
 "'3,577'",
 "'164'",
 "'434'",
 "'Hungary'",
 "'3,473'",
 "'448'",
 "'1371'",
 "'Iraq'",
 "'3,193'",
 "'117'",
 "'2,089'",
 "'Cameroon'",
 "'3,105'",
 "'140'",
 "'1,567'",
 "'Thailand'",
 "'3,025'",
 "'56'",
 "'2,854'",
 "'Azerbaijan'",
 "'2,980'",
 "'36'",
 "'1,886'",
 "'Greece'",
 "'2,810'",
 "'162'",
 "'1,464'",
 "'Uzbekistan'",
 "'2,691'",
 "'11'",
 "'2,158'",
 "'Puerto Rico'",
 "'2,542'",
 "'122'",
 "'850'",
 "'Guinea'",
 "'2,531'",
 "'15'",
 "'1,094'",
 "'Honduras'",
 "'2,460'",
 "'134'",
 "'264'",
 "'Senegal'",
 "'2,310'",
 "'25'",
 "'890'",
 "'Bosnia & Herzegovina'",
 "'2,236'",
 "'128'",
 "'1,336'",
 "'Croatia'",
 "'2,222'",
 "'95'",
 "'1,869'",
 "'Bulgaria'",
 "'2,175'",
 "'105'",
 "'573'",
 "'Ivory Coast'",
 "'2,017'",
 "'24'",
 "'942'",
 "'Sudan'",
 "'1,964'",
 "'91'",
 "'205'",
 "'Cuba'",
 "'1,840'",
 "'79'",
 "'1,425'",
 "'Iceland'",
 "'1,802'",
 "'10'",
 "'1,782'",
 "'Estonia'",
 "'1,770'",
 "'63'",
 "'934'",
 "'North Macedonia'",
 "'1,740'",
 "'97'",
 "'1,251'",
 "'Guatemala'",
 "'1,643'",
 "'30'",
 "'135'",
 "'Lithuania'",
 "'1,534'",
 "'55'",
 "'988'",
 "'Slovakia'",
 "'1,480'",
 "'27'",
 "'1,131'",
 "'Slovenia'",
 "'1,465'",
 "'103'",
 "'270'",
 "'DR Congo'",
 "'1,369'",
 "'61'",
 "'2129'",
 "'Djibouti'",
 "'1,309'",
 "'4'",
 "'935'",
 "'Somalia'",
 "'1,284'",
 "'53'",
 "'135'",
 "'El Salvador'",
 "'1,265'",
 "'25'",
 "'441'",
 "'Gabon'",
 "'1,209'",
 "'10'",
 "'219'",
 "'New Zealand'",
 "'1,148'",
 "'21'",
 "'1,428'",
 "'Tajikistan'",
 "'1,118'",
 "'33'",
 "'0'",
 "'Kyrgyzstan'",
 "'1,117'",
 "'14'",
 "'783'",
 "'USS'",
 "'Theodore Roosevelt'",
 "'1,102'",
 "'1'",
 "'53'",
 "'Charles de Gaulle'",
 "'1,081'",
 "'0'",
 "'0'",
 "'Hong Kong'",
 "'1,053'",
 "'4'",
 "'1,019'",
 "'Tunisia'",
 "'1,035'",
 "'45'",
 "'802'",
 "'Maldives'",
 "'1,031'",
 "'4'",
 "'46'",
 "'Latvia'",
 "'997'",
 "'19'",
 "'662'",
 "'Kosovo'",
 "'944'",
 "'29'",
 "'690'",
 "'Sri Lanka'",
 "'935'",
 "'9'",
 "'477'",
 "'Albania'",
 "'916'",
 "'31'",
 "'705'",
 "'Guinea-Bissau'",
 "'913'",
 "'3'",
 "'26'",
 "'Cyprus'",
 "'910'",
 "'17'",
 "'481'",
 "'Lebanon'",
 "'891'",
 "'26'",
 "'246'",
 "'Niger'",
 "'885'",
 "'51'",
 "'684'",
 "'Costa Rica'",
 "'843'",
 "'8'",
 "'542'",
 "'Mali'",
 "'806'",
 "'46'",
 "'455'",
 "'Kenya'",
 "'781'",
 "'45'",
 "'284'",
 "'Burkina Faso'",
 "'780'",
 "'51'",
 "'595'",
 "'Andorra'",
 "'761'",
 "'49'",
 "'604'",
 "'Paraguay'",
 "'759'",
 "'11'",
 "'193'",
 "'Uruguay'",
 "'732'",
 "'19'",
 "'553'",
 "'Diamond Princess'",
 "'712'",
 "'14'",
 "'653'",
 "'Georgia'",
 "'677'",
 "'12'",
 "'419'",
 "'Zambia'",
 "'668'",
 "'7'",
 "'152'",
 "'San Marino'",
 "'652'",
 "'41'",
 "'189'",
 "'Jordan'",
 "'596'",
 "'9'",
 "'401'",
 "'Equatorial Guinea'",
 "'594'",
 "'7'",
 "'22'",
 "'Malta'",
 "'532'",
 "'6'",
 "'458'",
 "'Jamaica'",
 "'511'",
 "'9'",
 "'121'",
 "'Tanzania'",
 "'509'",
 "'21'",
 "'183'",
 "'Venezuela'",
 "'459'",
 "'10'",
 "'229'",
 "'Sierra Leone'",
 "'447'",
 "'27'",
 "'97'",
 "'Taiwan'",
 "'440'",
 "'7'",
 "'383'",
 "'Chad'",
 "'428'",
 "'48'",
 "'88'",
 "'Congo'",
 "'391'",
 "'15'",
 "'87'",
 "'Palestine'",
 "'375'",
 "'2'",
 "'315'",
 "'Benin'",
 "'339'",
 "'2'",
 "'83'",
 "'Isle of Man'",
 "'334'",
 "'24'",
 "'285'",
 "'Mauritius'",
 "'332'",
 "'10'",
 "'322'",
 "'Cape Verde'",
 "'326'",
 "'2'",
 "'67'",
 "'Montenegro'",
 "'324'",
 "'9'",
 "'311'",
 "'Vietnam'",
 "'313'",
 "'0'",
 "'260'",
 "'Haiti'",
 "'310'",
 "'20'",
 "'19'",
 "'Luhansk PR'",
 "'308'",
 "'2'",
 "'53'",
 "'Central African Republic'",
 "'301'",
 "'0'",
 "'13'",
 "'Jersey'",
 "'297'",
 "'27'",
 "'226'",
 "'Ethiopia'",
 "'287'",
 "'5'",
 "'112'",
 "'Rwanda'",
 "'287'",
 "'0'",
 "'177'",
 "'Nepal'",
 "'276'",
 "'0'",
 "'36'",
 "'Togo'",
 "'263'",
 "'11'",
 "'96'",
 "'Guernsey'",
 "'252'",
 "'13'",
 "'231'",
 "'Donetsk PR'",
 "'246'",
 "'5'",
 "'36'",
 "'Madagascar'",
 "'238'",
 "'0'",
 "'112'",
 "'São Tomé & Príncipe'",
 "'235'",
 "'7'",
 "'4'",
 "'South Sudan'",
 "'231'",
 "'1'",
 "'3'",
 "'Liberia'",
 "'219'",
 "'20'",
 "'108'",
 "'Uganda'",
 "'203'",
 "'0'",
 "'63'",
 "'Eswatini'",
 "'190'",
 "'2'",
 "'66'",
 "'Faroe Islands'",
 "'187'",
 "'0'",
 "'187'",
 "'Myanmar'",
 "'182'",
 "'6'",
 "'89'",
 "'Guam'",
 "'154'",
 "'5'",
 "'128'",
 "'Costa Atlantica'",
 "'148'",
 "'0'",
 "'0'",
 "'Gibraltar'",
 "'147'",
 "'0'",
 "'144'",
 "'Brunei'",
 "'141'",
 "'1'",
 "'134'",
 "'Mongolia'",
 "'135'",
 "'0'",
 "'20'",
 "'Greg Mortimer'",
 "'128'",
 "'0'",
 "'No data'",
 "'Bermuda'",
 "'122'",
 "'9'",
 "'66'",
 "'Cambodia'",
 "'122'",
 "'0'",
 "'122'",
 "'Mozambique'",
 "'119'",
 "'0'",
 "'42'",
 "'Guyana'",
 "'116'",
 "'10'",
 "'43'",
 "'Trinidad & Tobago'",
 "'116'",
 "'8'",
 "'107'",
 "'Northern Cyprus'",
 "'108'",
 "'4'",
 "'104'",
 "'Yemen'",
 "'106'",
 "'15'",
 "'1'",
 "'Aruba'",
 "'101'",
 "'3'",
 "'93'",
 "'Bahamas'",
 "'96'",
 "'11'",
 "'41'",
 "'Monaco'",
 "'96'",
 "'4'",
 "'87'",
 "'Cayman Islands'",
 "'94'",
 "'1'",
 "'55'",
 "'Barbados'",
 "'85'",
 "'7'",
 "'65'",
 "'Liechtenstein'",
 "'82'",
 "'1'",
 "'55'",
 "'Sint Maarten'",
 "'77'",
 "'15'",
 "'54'",
 "'Somaliland'",
 "'70'",
 "'0'",
 "'15'",
 "'U.S. Virgin Islands'",
 "'69'",
 "'6'",
 "'61'",
 "'Libya'",
 "'64'",
 "'3'",
 "'28'",
 "'Malawi'",
 "'63'",
 "'3'",
 "'24'",
 "'French Polynesia'",
 "'60'",
 "'0'",
 "'59'",
 "'Syria'",
 "'50'",
 "'3'",
 "'36'",
 "'Angola'",
 "'48'",
 "'2'",
 "'14'",
 "'Macau'",
 "'45'",
 "'0'",
 "'43'",
 "'Zimbabwe'",
 "'42'",
 "'4'",
 "'13'",
 "'Eritrea'",
 "'39'",
 "'0'",
 "'38'",
 "'South Ossetia'",
 "'30'",
 "'0'",
 "'0'",
 "'Mauritania'",
 "'29'",
 "'3'",
 "'7'",
 "'Nicaragua'",
 "'25'",
 "'8'",
 "'7'",
 "'Antigua & Barbuda'",
 "'24'",
 "'3'",
 "'11'",
 "'East Timor'",
 "'24'",
 "'0'",
 "'21'",
 "'Botswana'",
 "'24'",
 "'1'",
 "'17'",
 "'The Gambia'",
 "'23'",
 "'1'",
 "'12'",
 "'Grenada'",
 "'22'",
 "'0'",
 "'14'",
 "'Bhutan'",
 "'21'",
 "'0'",
 "'5'",
 "'Artsakh'",
 "'20'",
 "'0'",
 "'8'",
 "'Laos'",
 "'19'",
 "'0'",
 "'14'",
 "'Northern Mariana Islands'",
 "'19'",
 "'2'",
 "'12'",
 "'Belize'",
 "'18'",
 "'2'",
 "'16'",
 "'Fiji'",
 "'18'",
 "'0'",
 "'15'",
 "'New Caledonia'",
 "'18'",
 "'0'",
 "'18'",
 "'Saint Lucia'",
 "'18'",
 "'0'",
 "'18'",
 "'Abkhazia'",
 "'17'",
 "'1'",
 "'2'",
 "'Saint Vincent'",
 "'17'",
 "'0'",
 "'14'",
 "'Curaçao'",
 "'16'",
 "'1'",
 "'14'",
 "'Dominica'",
 "'16'",
 "'0'",
 "'15'",
 "'Namibia'",
 "'16'",
 "'0'",
 "'13'",
 "'Burundi'",
 "'15'",
 "'1'",
 "'7'",
 "'Saint Kitts & Nevis'",
 "'15'",
 "'0'",
 "'14'",
 "'Falkland Islands'",
 "'13'",
 "'0'",
 "'13'",
 "'MS'",
 "'Zaandam'",
 "'13'",
 "'4'",
 "'No data'",
 "'Coral Princess'",
 "'12'",
 "'2'",
 "'No data'",
 "'Turks & Caicos Islands'",
 "'12'",
 "'1'",
 "'10'",
 "'Vatican City'",
 "'12'",
 "'0'",
 "'2'",
 "'Comoros'",
 "'11'",
 "'1'",
 "'3'",
 "'Greenland'",
 "'11'",
 "'0'",
 "'11'",
 "'Montserrat'",
 "'11'",
 "'1'",
 "'10'",
 "'Seychelles'",
 "'11'",
 "'0'",
 "'7'",
 "'Suriname'",
 "'10'",
 "'1'",
 "'9'",
 "'British Virgin Islands'",
 "'8'",
 "'1'",
 "'6'",
 "'HNLMS'",
 "'Dolfijn'",
 "'8'",
 "'0'",
 "'No data'",
 "'Papua New Guinea'",
 "'8'",
 "'0'",
 "'8'",
 "'Anguilla'",
 "'3'",
 "'0'",
 "'3'",
 "'Bonaire'",
 "'2'",
 "'0'",
 "'2'",
 "'Saba'",
 "'2'",
 "'0'",
 "'2'",
 "'Sint Eustatius'",
 "'2'",
 "'0'",
 "'2'",
 "'Lesotho'",
 "'1'",
 "'0'",
 "'0'",
 "'Saint Pierre & Miquelon'",
 "'1'",
 "'0'",
 "'1'",
 "'As of 16 May 2020 ('",
 "'UTC'",
 "') · History of cases:'",
 "'China'",
 "','",
 "'international'",
 "'Notes'",
 "'^'",
 "'Countries, territories, and international conveyances where cases were diagnosed. The nationality of the infected and the origin of infection may vary. For some countries, cases are split into respective territories and noted accordingly.'",
 "'^'",
 "'This number shows the cumulative number of confirmed human cases reported to date. The actual number of infections and cases is likely to be higher than reported.'",
 "'The total number of cases may not necessarily add up due to the frequency of values being updated for each location.'",
 "'Reporting criteria and'",
 "'testing capacity'",
 "'varies between countries.'",
 "'^'",
 "'Total deaths may not necessarily add up due to the frequency of values updating for each location. Reporting criteria varies between countries.'",
 "'^'",
 "'Reported recoveries. May not correspond to actual current figures and not all recoveries may be reported. Total recoveries may not necessarily add up due to the frequency of values updating for each location.'",
 "'^'",
 "'United States'",
 "'Figures include cases identified on the'",
 "'Grand Princess'",
 "'.'",
 "'Figures do not include the'",
 "'unincorporated territories'",
 "'of Puerto Rico, Guam, Northern Mariana Islands, and U.S. Virgin Islands, all of which are listed separately.'",
 "'Not all states or overseas territories report recovery data.'",
 "'Cases include clinically diagnosed cases as per CDC guidelines.'",
 "'Recoveries and deaths include probable deaths and people released from quarantine as per CDC guidelines.'",
 "'Figures from the'",
 "'United States Department of Defense'",
 "'are only released on a branch-by branch basis since April 2020, without distinction between domestic and foreign deployment, and cases may be reported to local health authorities.'",
 "'Cases for the'",
 "'USS'",
 "'Theodore Roosevelt'",
 '", currently docked at Guam, are reported separate from national figures but included in the Navy\'s totals."',
 "'There is also one case reported from'",
 "'Guantanamo Bay Naval Base'",
 '"not included in any other nation or territory\'s counts."',
 "'Since April 2020, the'",
 "'United States Department of Defense'",
 "'has directed all bases, including Guantanamo Bay, to not publicize case statistics.'",
 "'^'",
 "'Russia'",
 "'Including cases from the'",
 "'disputed'",
 "'Crimea'",
 "'and'",
 "'Sevastopol'",
 "'.'",
 "'Excluding the cases from'",
 "'Diamond Princess'",
 '\'cruise ship which are classified as "on an international conveyance".\'',
 "'^'",
 "'United Kingdom'",
 "'Excluding all'",
 "'British Overseas Territories'",
 "'and'",
 "'Crown dependencies'",
 "'.'",
 "'As of 23 March 2020, the UK government does not publish the number of recoveries. The last update on 22 March reported 135 recovered patients.'",
 "'^'",
 "'Spain'",
 "'Excludes serology–confirmed cases.'",
 "'^'",
 "'Germany'",
 "'Not all state authorities count recoveries.'",
 "'Recoveries include estimations by the'",
 "'Robert Koch Institute'",
 "'.'",
 "'^'",
 "'France'",
 "'Including'",
 "'French overseas regions'",
 "'Saint Martin'",
 "'and'",
 ...]

In [160]:
for n in range(len(lst)):
    word=lst[n]
    new_string = word.replace("'", "")
    lst[n]=new_string

In [161]:
lst

['Locations',
 'Cases',
 'Deaths',
 'Recov.',
 '229',
 '4,563,458',
 '308,165',
 '1,649,275',
 'United States',
 '1,473,415',
 '88,237',
 '260,146',
 'Russia',
 '272,043',
 '2,537',
 '63,166',
 'United Kingdom',
 '236,711',
 '33,998',
 'No data',
 'Spain',
 '230,183',
 '27,459',
 '144,783',
 'Italy',
 '223,885',
 '31,610',
 '120,205',
 'Brazil',
 '220,291',
 '14,962',
 '84,970',
 'Germany',
 '175,699',
 '8,001',
 '151,700',
 'Turkey',
 '146,457',
 '4,055',
 '106,133',
 'France',
 '141,919',
 '27,529',
 '60,448',
 'Iran',
 '116,635',
 '6,902',
 '91,836',
 'India',
 '85,940',
 '2,752',
 '30,153',
 'Peru',
 '84,495',
 '2,392',
 '27,147',
 'China',
 '82,941',
 '4,633',
 '78,219',
 'Canada',
 '74,613',
 '5,562',
 '36,895',
 'Belgium',
 '54,644',
 '8,959',
 '14,301',
 'Saudi Arabia',
 '49,176',
 '292',
 '21,869',
 'Mexico',
 '45,032',
 '4,767',
 '30,451',
 'Netherlands',
 '43,681',
 '5,643',
 'No data',
 'Chile',
 '39,542',
 '394',
 '16,614',
 'Pakistan',
 '38,799',
 '834',
 '10,880',
 'Ecuador',
 '31,467',
 '3,594',
 '3,433',
 'Switzerland',
 '30,514',
 '1,595',
 '27,200',
 'Qatar',
 '29,425',
 '14',
 '3,546',
 'Sweden',
 '29,207',
 '3,646',
 '4,971',
 'Belarus',
 '28,681',
 '160',
 '9,498',
 'Portugal',
 '28,583',
 '1,190',
 '3,328',
 'Singapore',
 '27,356',
 '21',
 '7,248',
 'Ireland',
 '23,956',
 '1,518',
 '19,470',
 'United Arab Emirates',
 '21,831',
 '210',
 '7,328',
 'Bangladesh',
 '20,065',
 '298',
 '3,882',
 'Poland',
 '18,016',
 '907',
 '6,918',
 'Ukraine',
 '17,858',
 '497',
 '4,906',
 'Romania',
 '16,704',
 '1,081',
 '9,574',
 'Israel',
 '16,589',
 '266',
 '12,587',
 'Indonesia',
 '16,496',
 '1,076',
 '3,803',
 'Japan',
 '16,253',
 '729',
 '10,809',
 'Austria',
 '16,135',
 '628',
 '14,471',
 'Colombia',
 '14,216',
 '546',
 '3,460',
 'South Africa',
 '13,524',
 '247',
 '6,083',
 'Kuwait',
 '12,860',
 '96',
 '3,640',
 'Philippines',
 '12,305',
 '817',
 '2,561',
 'Dominican Republic',
 '11,739',
 '424',
 '3,3557',
 'Egypt',
 '11,228',
 '592',
 '3,363',
 'South Korea',
 '11,037',
 '262',
 '9,851',
 'Denmark',
 '10,791',
 '537',
 '8,959',
 'Serbia',
 '10,438',
 '225',
 '4,301',
 'Panama',
 '9,268',
 '266',
 '6,080',
 'Czech Republic',
 '8,406',
 '295',
 '5,381',
 'Norway',
 '8,219',
 '232',
 '7,114',
 'Argentina',
 '7,121',
 '353',
 '2,372',
 'Australia',
 '7,038',
 '98',
 '6,362',
 'Malaysia',
 '6,872',
 '113',
 '5,512',
 'Morocco',
 '6,652',
 '190',
 '3,400',
 'Algeria',
 '6,629',
 '536',
 '3,271',
 'Bahrain',
 '6,583',
 '12',
 '2,640',
 'Afghanistan',
 '6,402',
 '168',
 '778',
 'Finland',
 '6,228',
 '287',
 '4,300',
 'Kazakhstan',
 '5,850',
 '34',
 '2,707',
 'Moldova',
 '5,745',
 '202',
 '2,280',
 'Ghana',
 '5,638',
 '28',
 '1,460',
 'Nigeria',
 '5,450',
 '171',
 '1,320',
 'Oman',
 '4,625',
 '19',
 '1,350',
 'Armenia',
 '4,283',
 '55',
 '1,791',
 'Luxembourg',
 '3,923',
 '104',
 '3,682',
 'Bolivia',
 '3,577',
 '164',
 '434',
 'Hungary',
 '3,473',
 '448',
 '1371',
 'Iraq',
 '3,193',
 '117',
 '2,089',
 'Cameroon',
 '3,105',
 '140',
 '1,567',
 'Thailand',
 '3,025',
 '56',
 '2,854',
 'Azerbaijan',
 '2,980',
 '36',
 '1,886',
 'Greece',
 '2,810',
 '162',
 '1,464',
 'Uzbekistan',
 '2,691',
 '11',
 '2,158',
 'Puerto Rico',
 '2,542',
 '122',
 '850',
 'Guinea',
 '2,531',
 '15',
 '1,094',
 'Honduras',
 '2,460',
 '134',
 '264',
 'Senegal',
 '2,310',
 '25',
 '890',
 'Bosnia & Herzegovina',
 '2,236',
 '128',
 '1,336',
 'Croatia',
 '2,222',
 '95',
 '1,869',
 'Bulgaria',
 '2,175',
 '105',
 '573',
 'Ivory Coast',
 '2,017',
 '24',
 '942',
 'Sudan',
 '1,964',
 '91',
 '205',
 'Cuba',
 '1,840',
 '79',
 '1,425',
 'Iceland',
 '1,802',
 '10',
 '1,782',
 'Estonia',
 '1,770',
 '63',
 '934',
 'North Macedonia',
 '1,740',
 '97',
 '1,251',
 'Guatemala',
 '1,643',
 '30',
 '135',
 'Lithuania',
 '1,534',
 '55',
 '988',
 'Slovakia',
 '1,480',
 '27',
 '1,131',
 'Slovenia',
 '1,465',
 '103',
 '270',
 'DR Congo',
 '1,369',
 '61',
 '2129',
 'Djibouti',
 '1,309',
 '4',
 '935',
 'Somalia',
 '1,284',
 '53',
 '135',
 'El Salvador',
 '1,265',
 '25',
 '441',
 'Gabon',
 '1,209',
 '10',
 '219',
 'New Zealand',
 '1,148',
 '21',
 '1,428',
 'Tajikistan',
 '1,118',
 '33',
 '0',
 'Kyrgyzstan',
 '1,117',
 '14',
 '783',
 'USS',
 'Theodore Roosevelt',
 '1,102',
 '1',
 '53',
 'Charles de Gaulle',
 '1,081',
 '0',
 '0',
 'Hong Kong',
 '1,053',
 '4',
 '1,019',
 'Tunisia',
 '1,035',
 '45',
 '802',
 'Maldives',
 '1,031',
 '4',
 '46',
 'Latvia',
 '997',
 '19',
 '662',
 'Kosovo',
 '944',
 '29',
 '690',
 'Sri Lanka',
 '935',
 '9',
 '477',
 'Albania',
 '916',
 '31',
 '705',
 'Guinea-Bissau',
 '913',
 '3',
 '26',
 'Cyprus',
 '910',
 '17',
 '481',
 'Lebanon',
 '891',
 '26',
 '246',
 'Niger',
 '885',
 '51',
 '684',
 'Costa Rica',
 '843',
 '8',
 '542',
 'Mali',
 '806',
 '46',
 '455',
 'Kenya',
 '781',
 '45',
 '284',
 'Burkina Faso',
 '780',
 '51',
 '595',
 'Andorra',
 '761',
 '49',
 '604',
 'Paraguay',
 '759',
 '11',
 '193',
 'Uruguay',
 '732',
 '19',
 '553',
 'Diamond Princess',
 '712',
 '14',
 '653',
 'Georgia',
 '677',
 '12',
 '419',
 'Zambia',
 '668',
 '7',
 '152',
 'San Marino',
 '652',
 '41',
 '189',
 'Jordan',
 '596',
 '9',
 '401',
 'Equatorial Guinea',
 '594',
 '7',
 '22',
 'Malta',
 '532',
 '6',
 '458',
 'Jamaica',
 '511',
 '9',
 '121',
 'Tanzania',
 '509',
 '21',
 '183',
 'Venezuela',
 '459',
 '10',
 '229',
 'Sierra Leone',
 '447',
 '27',
 '97',
 'Taiwan',
 '440',
 '7',
 '383',
 'Chad',
 '428',
 '48',
 '88',
 'Congo',
 '391',
 '15',
 '87',
 'Palestine',
 '375',
 '2',
 '315',
 'Benin',
 '339',
 '2',
 '83',
 'Isle of Man',
 '334',
 '24',
 '285',
 'Mauritius',
 '332',
 '10',
 '322',
 'Cape Verde',
 '326',
 '2',
 '67',
 'Montenegro',
 '324',
 '9',
 '311',
 'Vietnam',
 '313',
 '0',
 '260',
 'Haiti',
 '310',
 '20',
 '19',
 'Luhansk PR',
 '308',
 '2',
 '53',
 'Central African Republic',
 '301',
 '0',
 '13',
 'Jersey',
 '297',
 '27',
 '226',
 'Ethiopia',
 '287',
 '5',
 '112',
 'Rwanda',
 '287',
 '0',
 '177',
 'Nepal',
 '276',
 '0',
 '36',
 'Togo',
 '263',
 '11',
 '96',
 'Guernsey',
 '252',
 '13',
 '231',
 'Donetsk PR',
 '246',
 '5',
 '36',
 'Madagascar',
 '238',
 '0',
 '112',
 'São Tomé & Príncipe',
 '235',
 '7',
 '4',
 'South Sudan',
 '231',
 '1',
 '3',
 'Liberia',
 '219',
 '20',
 '108',
 'Uganda',
 '203',
 '0',
 '63',
 'Eswatini',
 '190',
 '2',
 '66',
 'Faroe Islands',
 '187',
 '0',
 '187',
 'Myanmar',
 '182',
 '6',
 '89',
 'Guam',
 '154',
 '5',
 '128',
 'Costa Atlantica',
 '148',
 '0',
 '0',
 'Gibraltar',
 '147',
 '0',
 '144',
 'Brunei',
 '141',
 '1',
 '134',
 'Mongolia',
 '135',
 '0',
 '20',
 'Greg Mortimer',
 '128',
 '0',
 'No data',
 'Bermuda',
 '122',
 '9',
 '66',
 'Cambodia',
 '122',
 '0',
 '122',
 'Mozambique',
 '119',
 '0',
 '42',
 'Guyana',
 '116',
 '10',
 '43',
 'Trinidad & Tobago',
 '116',
 '8',
 '107',
 'Northern Cyprus',
 '108',
 '4',
 '104',
 'Yemen',
 '106',
 '15',
 '1',
 'Aruba',
 '101',
 '3',
 '93',
 'Bahamas',
 '96',
 '11',
 '41',
 'Monaco',
 '96',
 '4',
 '87',
 'Cayman Islands',
 '94',
 '1',
 '55',
 'Barbados',
 '85',
 '7',
 '65',
 'Liechtenstein',
 '82',
 '1',
 '55',
 'Sint Maarten',
 '77',
 '15',
 '54',
 'Somaliland',
 '70',
 '0',
 '15',
 'U.S. Virgin Islands',
 '69',
 '6',
 '61',
 'Libya',
 '64',
 '3',
 '28',
 'Malawi',
 '63',
 '3',
 '24',
 'French Polynesia',
 '60',
 '0',
 '59',
 'Syria',
 '50',
 '3',
 '36',
 'Angola',
 '48',
 '2',
 '14',
 'Macau',
 '45',
 '0',
 '43',
 'Zimbabwe',
 '42',
 '4',
 '13',
 'Eritrea',
 '39',
 '0',
 '38',
 'South Ossetia',
 '30',
 '0',
 '0',
 'Mauritania',
 '29',
 '3',
 '7',
 'Nicaragua',
 '25',
 '8',
 '7',
 'Antigua & Barbuda',
 '24',
 '3',
 '11',
 'East Timor',
 '24',
 '0',
 '21',
 'Botswana',
 '24',
 '1',
 '17',
 'The Gambia',
 '23',
 '1',
 '12',
 'Grenada',
 '22',
 '0',
 '14',
 'Bhutan',
 '21',
 '0',
 '5',
 'Artsakh',
 '20',
 '0',
 '8',
 'Laos',
 '19',
 '0',
 '14',
 'Northern Mariana Islands',
 '19',
 '2',
 '12',
 'Belize',
 '18',
 '2',
 '16',
 'Fiji',
 '18',
 '0',
 '15',
 'New Caledonia',
 '18',
 '0',
 '18',
 'Saint Lucia',
 '18',
 '0',
 '18',
 'Abkhazia',
 '17',
 '1',
 '2',
 'Saint Vincent',
 '17',
 '0',
 '14',
 'Curaçao',
 '16',
 '1',
 '14',
 'Dominica',
 '16',
 '0',
 '15',
 'Namibia',
 '16',
 '0',
 '13',
 'Burundi',
 '15',
 '1',
 '7',
 'Saint Kitts & Nevis',
 '15',
 '0',
 '14',
 'Falkland Islands',
 '13',
 '0',
 '13',
 'MS',
 'Zaandam',
 '13',
 '4',
 'No data',
 'Coral Princess',
 '12',
 '2',
 'No data',
 'Turks & Caicos Islands',
 '12',
 '1',
 '10',
 'Vatican City',
 '12',
 '0',
 '2',
 'Comoros',
 '11',
 '1',
 '3',
 'Greenland',
 '11',
 '0',
 '11',
 'Montserrat',
 '11',
 '1',
 '10',
 'Seychelles',
 '11',
 '0',
 '7',
 'Suriname',
 '10',
 '1',
 '9',
 'British Virgin Islands',
 '8',
 '1',
 '6',
 'HNLMS',
 'Dolfijn',
 '8',
 '0',
 'No data',
 'Papua New Guinea',
 '8',
 '0',
 '8',
 'Anguilla',
 '3',
 '0',
 '3',
 'Bonaire',
 '2',
 '0',
 '2',
 'Saba',
 '2',
 '0',
 '2',
 'Sint Eustatius',
 '2',
 '0',
 '2',
 'Lesotho',
 '1',
 '0',
 '0',
 'Saint Pierre & Miquelon',
 '1',
 '0',
 '1',
 'As of 16 May 2020 (',
 'UTC',
 ') · History of cases:',
 'China',
 ',',
 'international',
 'Notes',
 '^',
 'Countries, territories, and international conveyances where cases were diagnosed. The nationality of the infected and the origin of infection may vary. For some countries, cases are split into respective territories and noted accordingly.',
 '^',
 'This number shows the cumulative number of confirmed human cases reported to date. The actual number of infections and cases is likely to be higher than reported.',
 'The total number of cases may not necessarily add up due to the frequency of values being updated for each location.',
 'Reporting criteria and',
 'testing capacity',
 'varies between countries.',
 '^',
 'Total deaths may not necessarily add up due to the frequency of values updating for each location. Reporting criteria varies between countries.',
 '^',
 'Reported recoveries. May not correspond to actual current figures and not all recoveries may be reported. Total recoveries may not necessarily add up due to the frequency of values updating for each location.',
 '^',
 'United States',
 'Figures include cases identified on the',
 'Grand Princess',
 '.',
 'Figures do not include the',
 'unincorporated territories',
 'of Puerto Rico, Guam, Northern Mariana Islands, and U.S. Virgin Islands, all of which are listed separately.',
 'Not all states or overseas territories report recovery data.',
 'Cases include clinically diagnosed cases as per CDC guidelines.',
 'Recoveries and deaths include probable deaths and people released from quarantine as per CDC guidelines.',
 'Figures from the',
 'United States Department of Defense',
 'are only released on a branch-by branch basis since April 2020, without distinction between domestic and foreign deployment, and cases may be reported to local health authorities.',
 'Cases for the',
 'USS',
 'Theodore Roosevelt',
 '", currently docked at Guam, are reported separate from national figures but included in the Navys totals."',
 'There is also one case reported from',
 'Guantanamo Bay Naval Base',
 '"not included in any other nation or territorys counts."',
 'Since April 2020, the',
 'United States Department of Defense',
 'has directed all bases, including Guantanamo Bay, to not publicize case statistics.',
 '^',
 'Russia',
 'Including cases from the',
 'disputed',
 'Crimea',
 'and',
 'Sevastopol',
 '.',
 'Excluding the cases from',
 'Diamond Princess',
 'cruise ship which are classified as "on an international conveyance".',
 '^',
 'United Kingdom',
 'Excluding all',
 'British Overseas Territories',
 'and',
 'Crown dependencies',
 '.',
 'As of 23 March 2020, the UK government does not publish the number of recoveries. The last update on 22 March reported 135 recovered patients.',
 '^',
 'Spain',
 'Excludes serology–confirmed cases.',
 '^',
 'Germany',
 'Not all state authorities count recoveries.',
 'Recoveries include estimations by the',
 'Robert Koch Institute',
 '.',
 '^',
 'France',
 'Including',
 'French overseas regions',
 'Saint Martin',
 'and',
 ...]

In [162]:
df = pd.DataFrame(np.array(lst).reshape(342,4))

In [163]:
data=df[:50]

In [164]:
data

                       0          1        2          3
0              Locations      Cases   Deaths     Recov.
1                    229  4,563,458  308,165  1,649,275
2          United States  1,473,415   88,237    260,146
3                 Russia    272,043    2,537     63,166
4         United Kingdom    236,711   33,998    No data
5                  Spain    230,183   27,459    144,783
6                  Italy    223,885   31,610    120,205
7                 Brazil    220,291   14,962     84,970
8                Germany    175,699    8,001    151,700
9                 Turkey    146,457    4,055    106,133
10                France    141,919   27,529     60,448
11                  Iran    116,635    6,902     91,836
12                 India     85,940    2,752     30,153
13                  Peru     84,495    2,392     27,147
14                 China     82,941    4,633     78,219
15                Canada     74,613    5,562     36,895
16               Belgium     54,644    8,959     14,301
17          Saudi Arabia     49,176      292     21,869
18                Mexico     45,032    4,767     30,451
19           Netherlands     43,681    5,643    No data
20                 Chile     39,542      394     16,614
21              Pakistan     38,799      834     10,880
22               Ecuador     31,467    3,594      3,433
23           Switzerland     30,514    1,595     27,200
24                 Qatar     29,425       14      3,546
25                Sweden     29,207    3,646      4,971
26               Belarus     28,681      160      9,498
27              Portugal     28,583    1,190      3,328
28             Singapore     27,356       21      7,248
29               Ireland     23,956    1,518     19,470
30  United Arab Emirates     21,831      210      7,328
31            Bangladesh     20,065      298      3,882
32                Poland     18,016      907      6,918
33               Ukraine     17,858      497      4,906
34               Romania     16,704    1,081      9,574
35                Israel     16,589      266     12,587
36             Indonesia     16,496    1,076      3,803
37                 Japan     16,253      729     10,809
38               Austria     16,135      628     14,471
39              Colombia     14,216      546      3,460
40          South Africa     13,524      247      6,083
41                Kuwait     12,860       96      3,640
42           Philippines     12,305      817      2,561
43    Dominican Republic     11,739      424     3,3557
44                 Egypt     11,228      592      3,363
45           South Korea     11,037      262      9,851
46               Denmark     10,791      537      8,959
47                Serbia     10,438      225      4,301
48                Panama      9,268      266      6,080
49        Czech Republic      8,406      295      5,381

In [165]:
data.columns = data.iloc[0]

In [166]:
data=data.drop(0)

In [167]:
data=data.drop(1)

In [168]:
data

0              Locations      Cases  Deaths   Recov.
2          United States  1,473,415  88,237  260,146
3                 Russia    272,043   2,537   63,166
4         United Kingdom    236,711  33,998  No data
5                  Spain    230,183  27,459  144,783
6                  Italy    223,885  31,610  120,205
7                 Brazil    220,291  14,962   84,970
8                Germany    175,699   8,001  151,700
9                 Turkey    146,457   4,055  106,133
10                France    141,919  27,529   60,448
11                  Iran    116,635   6,902   91,836
12                 India     85,940   2,752   30,153
13                  Peru     84,495   2,392   27,147
14                 China     82,941   4,633   78,219
15                Canada     74,613   5,562   36,895
16               Belgium     54,644   8,959   14,301
17          Saudi Arabia     49,176     292   21,869
18                Mexico     45,032   4,767   30,451
19           Netherlands     43,681   5,643  No data
20                 Chile     39,542     394   16,614
21              Pakistan     38,799     834   10,880
22               Ecuador     31,467   3,594    3,433
23           Switzerland     30,514   1,595   27,200
24                 Qatar     29,425      14    3,546
25                Sweden     29,207   3,646    4,971
26               Belarus     28,681     160    9,498
27              Portugal     28,583   1,190    3,328
28             Singapore     27,356      21    7,248
29               Ireland     23,956   1,518   19,470
30  United Arab Emirates     21,831     210    7,328
31            Bangladesh     20,065     298    3,882
32                Poland     18,016     907    6,918
33               Ukraine     17,858     497    4,906
34               Romania     16,704   1,081    9,574
35                Israel     16,589     266   12,587
36             Indonesia     16,496   1,076    3,803
37                 Japan     16,253     729   10,809
38               Austria     16,135     628   14,471
39              Colombia     14,216     546    3,460
40          South Africa     13,524     247    6,083
41                Kuwait     12,860      96    3,640
42           Philippines     12,305     817    2,561
43    Dominican Republic     11,739     424   3,3557
44                 Egypt     11,228     592    3,363
45           South Korea     11,037     262    9,851
46               Denmark     10,791     537    8,959
47                Serbia     10,438     225    4,301
48                Panama      9,268     266    6,080
49        Czech Republic      8,406     295    5,381

In [169]:
import csv
d=data.to_csv('COVID.csv')